#! /bin/bash

function testInput() {
    if [[ -z $1 ]]; then
        echo -e "You must pass in your home directory"
        echo -e "for instance:"
        echo -e "  ./modService bcuser"
        exit 1
    fi
}

sed -i "s/home\/\([^/]*\)/home\/$USER/g" $SERVICE_FILE
sed -i "s/SERVICE_FILE/$SERVICE_FILE/g" setup-service start-service stop-service
sed -i "s/User\=\([^/]*\)/User\=$USER/g" $SERVICE_FILE
sed -i "s/Group\=\([^/]*\)/Group\=$USER/g" $SERVICE_FILE