#! /bin/bash

function copyService() {
    ln -s $HOME/Git/writings/Tech/Markdown/ElvenImagePicker $HOME/bin/eip
    sudo cp -v eip.service /etc/systemd/system/.
    sudo systemctl enable eip.service
    sudo systemctl start eip.service
}

./mod-service $1 && copyService
